language: java
before_script:
- echo "Starting build"
script:
- cd Lab4_PR27
- mvn clean package
- mvn package
after_script:
- echo "Script finished"
after_succes:
- echo "Build ready"
- ls -l $TRAVIS_BUILD_DIR/target
after_failure:
- echo "Build failure"
